package onetomany.Notifications;

public enum NotificationType {
    NEW_MESSAGE,
    ITEM_LIKED,
    ITEM_SOLD,
    ITEM_PURCHASED,
    PRICE_DROP,
    NEW_ITEM_FROM_SELLER,
    REPORT_UPDATE,
    ACCOUNT_WARNING,
    ACCOUNT_SUSPENDED,
    TRANSACTION_PENDING,
    TRANSACTION_COMPLETED,
    TRANSACTION_CANCELLED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    LOW_STOCK_ALERT,
    OUT_OF_STOCK_ALERT,
    PAYMENT_RECEIVED,
    REFUND_PROCESSED,
    SYSTEM_ANNOUNCEMENT
}
